// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheWeekendGolfer.Web.Data;

namespace TheWeekendGolfer.Data.GolfDB.Migrations
{
    [DbContext(typeof(GolfDbContext))]
    partial class GolfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheWeekendGolfer.Web.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Holes");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<int>("Par");

                    b.Property<decimal>("ScratchRating");

                    b.Property<decimal>("Slope");

                    b.Property<string>("TeeName");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("TheWeekendGolfer.Web.Models.GolfRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CourseId");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("GolfRounds");
                });

            modelBuilder.Entity("TheWeekendGolfer.Web.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<decimal?>("Handicap");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TheWeekendGolfer.Web.Models.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("GolfRoundId");

                    b.Property<Guid?>("PlayerId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("GolfRoundId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("TheWeekendGolfer.Web.Models.GolfRound", b =>
                {
                    b.HasOne("TheWeekendGolfer.Web.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("TheWeekendGolfer.Web.Models.Score", b =>
                {
                    b.HasOne("TheWeekendGolfer.Web.Models.GolfRound")
                        .WithMany("Scores")
                        .HasForeignKey("GolfRoundId");

                    b.HasOne("TheWeekendGolfer.Web.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
